# Use nightly fmt

# in VSCode (settings.json):
# "rust-analyzer.rustfmt.extraArgs": [
#     "+nightly"
# ],
# and have nightly installed, of course

comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Crate"
imports_layout = "Vertical"
wrap_comments = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
